# Generated by Django 3.2.14 on 2022-07-28 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='created',
        ),
        migrations.RemoveField(
            model_name='question',
            name='modified',
        ),
    ]
