# Generated by Django 3.2.14 on 2022-08-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tags_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='name',
            field=models.CharField(default='python', max_length=20),
            preserve_default=False,
        ),
    ]
