# Generated by Django 3.2.14 on 2022-08-19 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tags_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='name',
        ),
    ]
