# Generated by Django 3.2.14 on 2022-08-06 14:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220801_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_body',
            field=ckeditor.fields.RichTextField(max_length=500),
        ),
    ]
