# Generated by Django 3.2.14 on 2022-08-15 20:17

import daryaft.users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_remove_answer_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='User',
            field=models.ForeignKey(default=daryaft.users.models.User, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
