# Generated by Django 3.2.14 on 2022-08-16 02:20

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_answer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(default=core.models.question, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.question'),
        ),
    ]
