# Generated by Django 3.2.14 on 2022-09-02 07:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_auto_20220901_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='User',
            new_name='user',
        ),
        migrations.AddField(
            model_name='answer',
            name='downvotes',
            field=models.ManyToManyField(related_name='answer_downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='upvotes',
            field=models.ManyToManyField(related_name='answer_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
