# Generated by Django 3.2.14 on 2022-08-16 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_answer_question_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
    ]
