# Generated by Django 3.2.14 on 2022-09-07 12:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20220905_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downvote',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='downvote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='user',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_body',
            field=ckeditor.fields.RichTextField(max_length=1500),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='DownVote',
        ),
        migrations.DeleteModel(
            name='UpVote',
        ),
    ]
