# Generated by Django 3.2.14 on 2022-09-09 05:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20220907_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=ckeditor.fields.RichTextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_body',
            field=ckeditor.fields.RichTextField(max_length=20000),
        ),
    ]
