# Generated by Django 3.2.14 on 2022-09-09 06:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20220909_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=ckeditor.fields.RichTextField(max_length=10000),
        ),
    ]
