# Generated by Django 3.2.14 on 2022-08-16 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_answer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='like',
        ),
    ]
