# Generated by Django 3.2.14 on 2022-08-16 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_question_id_answer_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='question_id',
        ),
    ]
